# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrollID', models.CharField(max_length=40)),
                ('scrollFrom', models.CharField(max_length=80)),
                ('scrollTo', models.CharField(max_length=80)),
                ('scrollMessage', models.CharField(max_length=1024)),
                ('regDate', models.DateTimeField(verbose_name='date registered')),
                ('pubDate', models.DateTimeField(verbose_name='date published')),
                ('isPublished', models.BooleanField()),
            ],
        ),
    ]
