# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scroll',
            old_name='isPublished',
            new_name='published',
        ),
    ]
