# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon', '0003_auto_20160328_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scroll',
            name='pubDate',
        ),
        migrations.RemoveField(
            model_name='scroll',
            name='published',
        ),
        migrations.RemoveField(
            model_name='scroll',
            name='regDate',
        ),
        migrations.RemoveField(
            model_name='scroll',
            name='scrollFrom',
        ),
        migrations.RemoveField(
            model_name='scroll',
            name='scrollTo',
        ),
    ]
